### ISSUE TITLE
xxl-job的agent转换会开源吗?

### ISSUE THREAD

**Issue by ccwxl** [wuwen5/ojdbc-mysql2oracle#7]

**Comment by wuwen5** [comment]
就是这个，目前支持xxl-job和 nacos, xxl-job 支持驱动的配置，可以不用配置agent

```
spring.datasource.driver-class-name=com.cenboomh.commons.ojdbc.driver.MysqlToOracleDriver
```

agent的方式主要是用于开源项目数据库驱动类不支持配置的情况，比如nacos-1.4.x

**Comment by ccwxl** [comment]
nacos2.0 测试过没?

**Comment by wuwen5** [comment]
> nacos2.0 测试过没?

目前没有测2.0,  对比了一下2.0```ExternalStoragePersistServiceImpl```sql这部分差异并不大，感兴趣可以去测试一下, 应该可以支持，如有问题欢迎反馈.
